// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1id37Im0XGtm59vW9-Ihomc4ANTdqEnk',
    appId: '1:321387848536:web:e3db9c74a0738d0db33b2d',
    messagingSenderId: '321387848536',
    projectId: 'chatapp-60b18',
    authDomain: 'chatapp-60b18.firebaseapp.com',
    storageBucket: 'chatapp-60b18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8PuI2VaYEq81udDohIEtUXX1MmsK33I',
    appId: '1:321387848536:android:debd867fcbc6d916b33b2d',
    messagingSenderId: '321387848536',
    projectId: 'chatapp-60b18',
    storageBucket: 'chatapp-60b18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33crVFk6I3EngjJ5OAdCz_C34S70tnS0',
    appId: '1:321387848536:ios:0929857c7d25f7f9b33b2d',
    messagingSenderId: '321387848536',
    projectId: 'chatapp-60b18',
    storageBucket: 'chatapp-60b18.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1id37Im0XGtm59vW9-Ihomc4ANTdqEnk',
    appId: '1:321387848536:web:5632ea8527a29ff2b33b2d',
    messagingSenderId: '321387848536',
    projectId: 'chatapp-60b18',
    authDomain: 'chatapp-60b18.firebaseapp.com',
    storageBucket: 'chatapp-60b18.appspot.com',
  );
}
